# Generated by Django 4.2.7 on 2025-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='category',
            field=models.CharField(choices=[('thanksgiving', 'Thanksgiving'), ('wonder', 'Wonder'), ('faith', 'Faith'), ('contemplation', 'Contemplation'), ('reflection', 'Reflection')], max_length=50),
        ),
    ]
