# Generated by Django 4.2.7 on 2025-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testimonial_prayertestimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='volume',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload audio file (MP3, WAV, etc.)', null=True, upload_to='volume_audio/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('peace', 'Peace'), ('gratitude', 'Gratitude'), ('strength', 'Strength'), ('worship', 'Worship'), ('faithfulness', 'Faithfulness'), ('guidance', 'Guidance')], max_length=50),
        ),
    ]
