# Generated by Django 4.2.7 on 2025-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_volume_audio_url_volume_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('devotional', 'Devotional'), ('poetry', 'Poetry'), ('memoir', 'Memoir'), ('study', 'Bible Study'), ('inspiration', 'Inspiration')], max_length=50)),
                ('author', models.CharField(default='Uzo', max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('preview_pdf', models.FileField(blank=True, help_text='Upload preview PDF', null=True, upload_to='book_previews/')),
                ('purchase_link', models.URLField(blank=True, help_text='Link to purchase (Amazon, etc.)')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('sales_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
